apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: <namespace>
  labels:
    app: money-tracker-ui
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: money-tracker-ui
  type: LoadBalancer